services:
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  db:
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    image: postgres:15
    container_name: superset_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_home:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  superset:
    image: juliocesaracostalopez01/supersetv3 #imagen custom de superset
    container_name: superset_app
    command: >
      bash -c "superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger"
    ports:
      - 8088:8088
    restart: unless-stopped
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    depends_on:
      - superset-init
    volumes:
      - superset_home:/app/superset_home
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      SUPERSET_ENABLE_PROXY_FIX: True
      SUPERSET_WEBSERVER_ADDRESS: 0.0.0.0
      SUPERSET_WEBSERVER_PORT: 8088

  superset-init:
    image: juliocesaracostalopez01/supersetv3
    container_name: superset_init
    command: >
      sh -c "sleep 10 &&
      superset fab create-admin
      --username admin
      --firstname Admin
      --lastname User
      --email admin@superset.com
      --password admin &&
      superset db upgrade &&
      superset init"
    restart: on-failure
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    depends_on:
      - db
      - redis
    volumes:
      - superset_home:/app/superset_home
    environment:
      SUPERSET_LOAD_EXAMPLES: "${SUPERSET_LOAD_EXAMPLES:-no}"
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"

  superset-worker:
    image: juliocesaracostalopez01/supersetv3
    container_name: superset_worker
    command: >
      bash -c "celery --app=superset.tasks.celery_app:app worker --pool=prefork -O fair -c 4"
    restart: unless-stopped
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    depends_on:
      - superset-init
    volumes:
      - superset_home:/app/superset_home
      - ./celerybeat-schedule:/tmp/celerybeat-schedule
      - ./celerybeat-schedule:/home/superset/celerybeat-schedule
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      CELERY_BROKER_URL: "redis://superset_cache:6379/0"  # Fuerza el uso de Redis
      CELERY_RESULT_BACKEND: "redis://superset_cache:6379/0"

  superset-worker-beat:
    image: juliocesaracostalopez01/supersetv3
    user: "0:0"  # Ejecuta como root
    container_name: superset_worker_beat
    command: >
      bash -c "celery --app=superset.tasks.celery_app:app beat --pidfile=/tmp/celerybeat.pid -l INFO"
    restart: unless-stopped
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    depends_on:
      - superset-worker
    volumes:
      - superset_home:/app/superset_home
      - ./celerybeat:/var/lib/celery
      - ./celerybeat-schedule:/tmp/celerybeat-schedule
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      CELERYBEAT_SCHEDULE_FILENAME: /var/lib/celery/celerybeat-schedule

volumes:
  superset_home:
  db_home:
  redis:
